name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 添加上游仓库
        run: git remote add upstream https://github.com/waditu/czsc.git

      - name: 拉取上游变更
        run: git fetch upstream

      - name: 合并并推送
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git merge upstream/main --allow-unrelated-histories
          git push origin main
