name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 添加上游仓库
        run: git remote add upstream https://github.com/waditu/czsc.git

      - name: 拉取上游变更
        run: git fetch upstream

      - name: 合并并推送
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # git merge upstream/master --allow-unrelated-histories
          # git merge -X theirs upstream/master  # 强制接受上游版本（覆盖你的修改）
          git fetch upstream
          git merge upstream/master --no-edit
          # git reset --hard upstream/master  # 强制将本地分支重置到上游状态
          git push origin master --force    # 覆盖远程仓库
          # git push origin master
